dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.58
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.58
- name: nodey243
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.2
- name: nodey246
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: sandiegocool
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
- name: sandiegorocks
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1
